language: android

sudo: false

before_install:
  - yes | sdkmanager "platforms;android-27"

env:
  global:
  - ANDROID_API_LEVEL=27
  - ANDROID_EMU_API_LEVEL=27
  - ANDROID_ABI=armeabi-v7a
  - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
  - QEMU_AUDIO_DRV=none # Remove audio

# Emulator Management: Create, Start and Wait
before_script:
  - android list targets
  - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi google_apis/$ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-$ANDROID_API_LEVEL
  - extra-android-m2repository
  - extra-android-support
  - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMU_API_LEVEL
