language: android

sudo: false

before_install:
  - yes | sdkmanager "platforms;android-27"

android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-25
  - extra-android-m2repository
  - extra-android-support
